# input folder with the files
inputs_dir = "inputs" # inputs for one representative period

# input files for sets
input_file_set_g   = "iGEP_set_g.csv"
input_file_set_l   = "iGEP_set_l.csv"
input_file_set_n   = "iGEP_set_n.csv"

# input files for data
input_file_dem     = "iGEP_data_demand.csv"
input_file_gen_ava = "iGEP_data_generation_availability.csv"
input_file_gen     = "iGEP_data_generation.csv"
input_file_lines   = "iGEP_data_transmission_lines.csv"
