

[locations]
[locations.work]
latitude = 52.1

[files]
excel_file_source_sheet = 'Sheet1'
[files.output]
dataframe_name = "example"
folder = "Output_Omar"
excel_sheet_name = "test_sheet"
excel_anchor_cell = "C26"
chosen_output_formats = ["csv","feather","h5","parquet","json","xlsx"]
[files.output.formats]
#Set to true or false if you want the writing function to write to these formats
csv = true
[files.input]
source_folder = 'Input_Omar'

[example_dataframe]
countries = ["Netehrlands","Switzerland","Kiribati","India"]
energy_levels = [1.989,1.602,0.26,0.42]